services:
  postgres:
    image: postgres:16
    container_name: chess-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: chess
      POSTGRES_USER: chess_user
      POSTGRES_PASSWORD: chess_password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: